$file = 'src\app\dashboard\marketplace\page.tsx'
$content = Get-Content $file -Raw

# 1. Update fetchListings to filter by campus and add allSchools dep
$old = "    const fetchListings = useCallback(async () => {`r`n        setLoading(true)`r`n        const { data: listingsData, error } = await supabase`r`n            .from('listings')`r`n            .select('*')`r`n            .eq('status', 'available')`r`n            .order('created_at', { ascending: false })`r`n`r`n        if (error) {`r`n            console.error('Error fetching listings:', error)`r`n            setLoading(false)`r`n            return`r`n        }`r`n`r`n        if (listingsData) {`r`n            const listingsWithImages = await Promise.all(`r`n                listingsData.map(async (listing) => {`r`n                    const images = await fetchListingImages(listing.id)`r`n                    return { ...listing, images }`r`n                })`r`n            )`r`n            setListings(listingsWithImages)`r`n        }`r`n        setLoading(false)`r`n        initialLoadDone.current = true`r`n    }, [fetchListingImages, supabase])"

$new = "    const fetchListings = useCallback(async () => {`r`n        setLoading(true)`r`n        let query = supabase`r`n            .from('listings')`r`n            .select('*')`r`n            .eq('status', 'available')`r`n            .order('promoted', { ascending: false })`r`n            .order('created_at', { ascending: false })`r`n`r`n        // Filter by campus unless user toggled all schools`r`n        if (campus && !allSchools) {`r`n            query = query.or(`"`"campus.eq.`$`{campus},campus.is.null`"`")`r`n        }`r`n`r`n        const { data: listingsData, error } = await query`r`n`r`n        if (error) {`r`n            console.error('Error fetching listings:', error)`r`n            setLoading(false)`r`n            return`r`n        }`r`n`r`n        if (listingsData) {`r`n            const listingsWithImages = await Promise.all(`r`n                listingsData.map(async (listing) => {`r`n                    const images = await fetchListingImages(listing.id)`r`n                    return { ...listing, images }`r`n                })`r`n            )`r`n            setListings(listingsWithImages)`r`n        }`r`n        setLoading(false)`r`n        initialLoadDone.current = true`r`n    }, [fetchListingImages, supabase, campus, allSchools])"

$content = $content.Replace($old, $new)

Set-Content $file $content -NoNewline
Write-Output "Done"
